apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-app-deployment
  labels:
    app: actions-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actions-app
  template:
    metadata:
      labels:
        app: actions-app
    spec:
      containers:
      - name: actions-app
        image: 872346933932.dkr.ecr.ap-south-1.amazonaws.com/github-actions:latest
        ports:
        - containerPort: 3000

